#include "loadgl.h"

#if USE_ANGLE_GLES
// OpenGL ES:

void (APIENTRY* bglAlphaFunc)(GLenum func, GLfloat ref);
void (APIENTRY* bglClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (APIENTRY* bglClearDepthf)(GLfloat d);
void (APIENTRY* bglClipPlanef)(GLenum p, const GLfloat* eqn);
void (APIENTRY* bglColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void (APIENTRY* bglDepthRangef)(GLfloat n, GLfloat f);
void (APIENTRY* bglFogf)(GLenum pname, GLfloat param);
void (APIENTRY* bglFogfv)(GLenum pname, const GLfloat* params);
void (APIENTRY* bglFrustumf)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
void (APIENTRY* bglGetClipPlanef)(GLenum plane, GLfloat* equation);
void (APIENTRY* bglGetFloatv)(GLenum pname, GLfloat* data);
void (APIENTRY* bglGetLightfv)(GLenum light, GLenum pname, GLfloat* params);
void (APIENTRY* bglGetMaterialfv)(GLenum face, GLenum pname, GLfloat* params);
void (APIENTRY* bglGetTexEnvfv)(GLenum target, GLenum pname, GLfloat* params);
void (APIENTRY* bglGetTexParameterfv)(GLenum target, GLenum pname, GLfloat* params);
void (APIENTRY* bglLightModelf)(GLenum pname, GLfloat param);
void (APIENTRY* bglLightModelfv)(GLenum pname, const GLfloat* params);
void (APIENTRY* bglLightf)(GLenum light, GLenum pname, GLfloat param);
void (APIENTRY* bglLightfv)(GLenum light, GLenum pname, const GLfloat* params);
void (APIENTRY* bglLineWidth)(GLfloat width);
void (APIENTRY* bglLoadMatrixf)(const GLfloat* m);
void (APIENTRY* bglMaterialf)(GLenum face, GLenum pname, GLfloat param);
void (APIENTRY* bglMaterialfv)(GLenum face, GLenum pname, const GLfloat* params);
void (APIENTRY* bglMultMatrixf)(const GLfloat* m);
void (APIENTRY* bglMultiTexCoord4f)(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void (APIENTRY* bglNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
void (APIENTRY* bglOrthof)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
void (APIENTRY* bglPointParameterf)(GLenum pname, GLfloat param);
void (APIENTRY* bglPointParameterfv)(GLenum pname, const GLfloat* params);
void (APIENTRY* bglPointSize)(GLfloat size);
void (APIENTRY* bglPolygonOffset)(GLfloat factor, GLfloat units);
void (APIENTRY* bglRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void (APIENTRY* bglScalef)(GLfloat x, GLfloat y, GLfloat z);
void (APIENTRY* bglTexEnvf)(GLenum target, GLenum pname, GLfloat param);
void (APIENTRY* bglTexEnvfv)(GLenum target, GLenum pname, const GLfloat* params);
void (APIENTRY* bglTexParameterf)(GLenum target, GLenum pname, GLfloat param);
void (APIENTRY* bglTexParameterfv)(GLenum target, GLenum pname, const GLfloat* params);
void (APIENTRY* bglTranslatef)(GLfloat x, GLfloat y, GLfloat z);
void (APIENTRY* bglActiveTexture)(GLenum texture);
void (APIENTRY* bglAlphaFuncx)(GLenum func, GLfixed ref);
void (APIENTRY* bglBindBuffer)(GLenum target, GLuint buffer);
void (APIENTRY* bglBindTexture)(GLenum target, GLuint texture);
void (APIENTRY* bglBlendFunc)(GLenum sfactor, GLenum dfactor);
void (APIENTRY* bglBufferData)(GLenum target, GLsizeiptr size, const void* data, GLenum usage);
void (APIENTRY* bglBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
void (APIENTRY* bglClear)(GLbitfield mask);
void (APIENTRY* bglClearColorx)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
void (APIENTRY* bglClearDepthx)(GLfixed depth);
void (APIENTRY* bglClearStencil)(GLint s);
void (APIENTRY* bglClientActiveTexture)(GLenum texture);
void (APIENTRY* bglClipPlanex)(GLenum plane, const GLfixed* equation);
void (APIENTRY* bglColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void (APIENTRY* bglColor4x)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
void (APIENTRY* bglColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void (APIENTRY* bglColorPointer)(GLint size, GLenum type, GLsizei stride, const void* pointer);
void (APIENTRY* bglCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
void (APIENTRY* bglCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data);
void (APIENTRY* bglCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void (APIENTRY* bglCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (APIENTRY* bglCullFace)(GLenum mode);
void (APIENTRY* bglDeleteBuffers)(GLsizei n, const GLuint* buffers);
void (APIENTRY* bglDeleteTextures)(GLsizei n, const GLuint* textures);
void (APIENTRY* bglDepthFunc)(GLenum func);
void (APIENTRY* bglDepthMask)(GLboolean flag);
void (APIENTRY* bglDepthRangex)(GLfixed n, GLfixed f);
void (APIENTRY* bglDisable)(GLenum cap);
void (APIENTRY* bglDisableClientState)(GLenum array);
void (APIENTRY* bglDrawArrays)(GLenum mode, GLint first, GLsizei count);
void (APIENTRY* bglDrawElements)(GLenum mode, GLsizei count, GLenum type, const void* indices);
void (APIENTRY* bglEnable)(GLenum cap);
void (APIENTRY* bglEnableClientState)(GLenum array);
void (APIENTRY* bglFinish)(void);
void (APIENTRY* bglFlush)(void);
void (APIENTRY* bglFogx)(GLenum pname, GLfixed param);
void (APIENTRY* bglFogxv)(GLenum pname, const GLfixed* param);
void (APIENTRY* bglFrontFace)(GLenum mode);
void (APIENTRY* bglFrustumx)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
void (APIENTRY* bglGetBooleanv)(GLenum pname, GLboolean* data);
void (APIENTRY* bglGetBufferParameteriv)(GLenum target, GLenum pname, GLint* params);
void (APIENTRY* bglGetClipPlanex)(GLenum plane, GLfixed* equation);
void (APIENTRY* bglGenBuffers)(GLsizei n, GLuint* buffers);
void (APIENTRY* bglGenTextures)(GLsizei n, GLuint* textures);
GLenum(APIENTRY* bglGetError)(void);
void (APIENTRY* bglGetFixedv)(GLenum pname, GLfixed* params);
void (APIENTRY* bglGetIntegerv)(GLenum pname, GLint* data);
void (APIENTRY* bglGetLightxv)(GLenum light, GLenum pname, GLfixed* params);
void (APIENTRY* bglGetMaterialxv)(GLenum face, GLenum pname, GLfixed* params);
void (APIENTRY* bglGetPointerv)(GLenum pname, void** params);
const GLubyte* (APIENTRY* bglGetString)(GLenum name);
void (APIENTRY* bglGetTexEnviv)(GLenum target, GLenum pname, GLint* params);
void (APIENTRY* bglGetTexEnvxv)(GLenum target, GLenum pname, GLfixed* params);
void (APIENTRY* bglGetTexParameteriv)(GLenum target, GLenum pname, GLint* params);
void (APIENTRY* bglGetTexParameterxv)(GLenum target, GLenum pname, GLfixed* params);
void (APIENTRY* bglHint)(GLenum target, GLenum mode);
GLboolean(APIENTRY* bglIsBuffer)(GLuint buffer);
GLboolean(APIENTRY* bglIsEnabled)(GLenum cap);
GLboolean(APIENTRY* bglIsTexture)(GLuint texture);
void (APIENTRY* bglLightModelx)(GLenum pname, GLfixed param);
void (APIENTRY* bglLightModelxv)(GLenum pname, const GLfixed* param);
void (APIENTRY* bglLightx)(GLenum light, GLenum pname, GLfixed param);
void (APIENTRY* bglLightxv)(GLenum light, GLenum pname, const GLfixed* params);
void (APIENTRY* bglLineWidthx)(GLfixed width);
void (APIENTRY* bglLoadIdentity)(void);
void (APIENTRY* bglLoadMatrixx)(const GLfixed* m);
void (APIENTRY* bglLogicOp)(GLenum opcode);
void (APIENTRY* bglMaterialx)(GLenum face, GLenum pname, GLfixed param);
void (APIENTRY* bglMaterialxv)(GLenum face, GLenum pname, const GLfixed* param);
void (APIENTRY* bglMatrixMode)(GLenum mode);
void (APIENTRY* bglMultMatrixx)(const GLfixed* m);
void (APIENTRY* bglMultiTexCoord4x)(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
void (APIENTRY* bglNormal3x)(GLfixed nx, GLfixed ny, GLfixed nz);
void (APIENTRY* bglNormalPointer)(GLenum type, GLsizei stride, const void* pointer);
void (APIENTRY* bglOrthox)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
void (APIENTRY* bglPixelStorei)(GLenum pname, GLint param);
void (APIENTRY* bglPointParameterx)(GLenum pname, GLfixed param);
void (APIENTRY* bglPointParameterxv)(GLenum pname, const GLfixed* params);
void (APIENTRY* bglPointSizex)(GLfixed size);
void (APIENTRY* bglPolygonOffsetx)(GLfixed factor, GLfixed units);
void (APIENTRY* bglPopMatrix)(void);
void (APIENTRY* bglPushMatrix)(void);
void (APIENTRY* bglReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
void (APIENTRY* bglRotatex)(GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
void (APIENTRY* bglSampleCoverage)(GLfloat value, GLboolean invert);
void (APIENTRY* bglSampleCoveragex)(GLclampx value, GLboolean invert);
void (APIENTRY* bglScalex)(GLfixed x, GLfixed y, GLfixed z);
void (APIENTRY* bglScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
void (APIENTRY* bglShadeModel)(GLenum mode);
void (APIENTRY* bglStencilFunc)(GLenum func, GLint ref, GLuint mask);
void (APIENTRY* bglStencilMask)(GLuint mask);
void (APIENTRY* bglStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
void (APIENTRY* bglTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const void* pointer);
void (APIENTRY* bglTexEnvi)(GLenum target, GLenum pname, GLint param);
void (APIENTRY* bglTexEnvx)(GLenum target, GLenum pname, GLfixed param);
void (APIENTRY* bglTexEnviv)(GLenum target, GLenum pname, const GLint* params);
void (APIENTRY* bglTexEnvxv)(GLenum target, GLenum pname, const GLfixed* params);
void (APIENTRY* bglTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
void (APIENTRY* bglTexParameteri)(GLenum target, GLenum pname, GLint param);
void (APIENTRY* bglTexParameterx)(GLenum target, GLenum pname, GLfixed param);
void (APIENTRY* bglTexParameteriv)(GLenum target, GLenum pname, const GLint* params);
void (APIENTRY* bglTexParameterxv)(GLenum target, GLenum pname, const GLfixed* params);
void (APIENTRY* bglTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
void (APIENTRY* bglTranslatex)(GLfixed x, GLfixed y, GLfixed z);
void (APIENTRY* bglVertexPointer)(GLint size, GLenum type, GLsizei stride, const void* pointer);
void (APIENTRY* bglViewport)(GLint x, GLint y, GLsizei width, GLsizei height);

static void* getproc_(const char* s, int* err, int fatal, int extension)
{
	void* t;
#if defined RENDERTYPESDL
	t = (void*)SDL_GL_GetProcAddress(s);
#elif defined _WIN32
	if (extension) t = (void*)bwglGetProcAddress(s);
	else t = (void*)GetProcAddress(hGLDLL, s);
#else
#error Need a dynamic loader for this platform...
#endif
	if (!t && fatal) {
		printf("Failed to find in OpenGL ES 1.1\n");
		*err = 1;
	}
	return t;
}
#define GETPROC(s)        getproc_(s,&err,1,0)

void GLESInit()
{
	int err = 0;
	bglAlphaFunc = GETPROC("glAlphaFunc");
	bglClearColor = GETPROC("glClearColor");
	bglClearDepthf = GETPROC("glClearDepthf");
	bglClipPlanef = GETPROC("glClipPlanef");
	bglColor4f = GETPROC("glColor4f");
	bglDepthRangef = GETPROC("glDepthRangef");
	bglFogf = GETPROC("glFogf");
	bglFogfv = GETPROC("glFogfv");
	bglFrustumf = GETPROC("glFrustumf");
	bglGetClipPlanef = GETPROC("glGetClipPlanef");
	bglGetFloatv = GETPROC("glGetFloatv");
	bglGetLightfv = GETPROC("glGetLightfv");
	bglGetMaterialfv = GETPROC("glGetMaterialfv");
	bglGetTexEnvfv = GETPROC("glGetTexEnvfv");
	bglGetTexParameterfv = GETPROC("glGetTexParameterfv");
	bglLightModelf = GETPROC("glLightModelf");
	bglLightModelfv = GETPROC("glLightModelfv");
	bglLightf = GETPROC("glLightf");
	bglLightfv = GETPROC("glLightfv");
	bglLineWidth = GETPROC("glLineWidth");
	bglLoadMatrixf = GETPROC("glLoadMatrixf");
	bglMaterialf = GETPROC("glMaterialf");
	bglMaterialfv = GETPROC("glMaterialfv");
	bglMultMatrixf = GETPROC("glMultMatrixf");
	bglMultiTexCoord4f = GETPROC("glMultiTexCoord4f");
	bglNormal3f = GETPROC("glNormal3f");
	bglOrthof = GETPROC("glOrthof");
	bglPointParameterf = GETPROC("glPointParameterf");
	bglPointParameterfv = GETPROC("glPointParameterfv");
	bglPointSize = GETPROC("glPointSize");
	bglPolygonOffset = GETPROC("glPolygonOffset");
	bglRotatef = GETPROC("glRotatef");
	bglScalef = GETPROC("glScalef");
	bglTexEnvf = GETPROC("glTexEnvf");
	bglTexEnvfv = GETPROC("glTexEnvfv");
	bglTexParameterf = GETPROC("glTexParameterf");
	bglTexParameterfv = GETPROC("glTexParameterfv");
	bglTranslatef = GETPROC("glTranslatef");
	bglActiveTexture = GETPROC("glActiveTexture");
	bglAlphaFuncx = GETPROC("glAlphaFuncx");
	bglBindBuffer = GETPROC("glBindBuffer");
	bglBindTexture = GETPROC("glBindTexture");
	bglBlendFunc = GETPROC("glBlendFunc");
	bglBufferData = GETPROC("glBufferData");
	bglBufferSubData = GETPROC("glBufferSubData");
	bglClear = GETPROC("glClear");
	bglClearColorx = GETPROC("glClearColorx");
	bglClearDepthx = GETPROC("glClearDepthx");
	bglClearStencil = GETPROC("glClearStencil");
	bglClientActiveTexture = GETPROC("glClientActiveTexture");
	bglClipPlanex = GETPROC("glClipPlanex");
	bglColor4ub = GETPROC("glColor4ub");
	bglColor4x = GETPROC("glColor4x");
	bglColorMask = GETPROC("glColorMask");
	bglColorPointer = GETPROC("glColorPointer");
	bglCompressedTexImage2D = GETPROC("glCompressedTexImage2D");
	bglCompressedTexSubImage2D = GETPROC("glCompressedTexSubImage2D");
	bglCopyTexImage2D = GETPROC("glCopyTexImage2D");
	bglCopyTexSubImage2D = GETPROC("glCopyTexSubImage2D");
	bglCullFace = GETPROC("glCullFace");
	bglDeleteBuffers = GETPROC("glDeleteBuffers");
	bglDeleteTextures = GETPROC("glDeleteTextures");
	bglDepthFunc = GETPROC("glDepthFunc");
	bglDepthMask = GETPROC("glDepthMask");
	bglDepthRangex = GETPROC("glDepthRangex");
	bglDisable = GETPROC("glDisable");
	bglDisableClientState = GETPROC("glDisableClientState");
	bglDrawArrays = GETPROC("glDrawArrays");
	bglDrawElements = GETPROC("glDrawElements");
	bglEnable = GETPROC("glEnable");
	bglEnableClientState = GETPROC("glEnableClientState");
	bglFinish = GETPROC("glFinish");
	bglFlush = GETPROC("glFlush");
	bglFogx = GETPROC("glFogx");
	bglFogxv = GETPROC("glFogxv");
	bglFrontFace = GETPROC("glFrontFace");
	bglFrustumx = GETPROC("glFrustumx");
	bglGetBooleanv = GETPROC("glGetBooleanv");
	bglGetBufferParameteriv = GETPROC("glGetBufferParameteriv");
	bglGetClipPlanex = GETPROC("glGetClipPlanex");
	bglGenBuffers = GETPROC("glGenBuffers");
	bglGenTextures = GETPROC("glGenTextures");
	bglGetError = GETPROC("glGetError");
	bglGetFixedv = GETPROC("glGetFixedv");
	bglGetIntegerv = GETPROC("glGetIntegerv");
	bglGetLightxv = GETPROC("glGetLightxv");
	bglGetMaterialxv = GETPROC("glGetMaterialxv");
	bglGetPointerv = GETPROC("glGetPointerv");
	bglGetString = GETPROC("glGetString");
	bglGetTexEnviv = GETPROC("glGetTexEnviv");
	bglGetTexEnvxv = GETPROC("glGetTexEnvxv");
	bglGetTexParameteriv = GETPROC("glGetTexParameteriv");
	bglGetTexParameterxv = GETPROC("glGetTexParameterxv");
	bglHint = GETPROC("glHint");
	bglIsBuffer = GETPROC("glIsBuffer");
	bglIsEnabled = GETPROC("glIsEnabled");
	bglIsTexture = GETPROC("glIsTexture");
	bglLightModelx = GETPROC("glLightModelx");
	bglLightModelxv = GETPROC("glLightModelxv");
	bglLightx = GETPROC("glLightx");
	bglLightxv = GETPROC("glLightxv");
	bglLineWidthx = GETPROC("glLineWidthx");
	bglLoadIdentity = GETPROC("glLoadIdentity");
	bglLoadMatrixx = GETPROC("glLoadMatrixx");
	bglLogicOp = GETPROC("glLogicOp");
	bglMaterialx = GETPROC("glMaterialx");
	bglMaterialxv = GETPROC("glMaterialxv");
	bglMatrixMode = GETPROC("glMatrixMode");
	bglMultMatrixx = GETPROC("glMultMatrixx");
	bglMultiTexCoord4x = GETPROC("glMultiTexCoord4x");
	bglNormal3x = GETPROC("glNormal3x");
	bglNormalPointer = GETPROC("glNormalPointer");
	bglOrthox = GETPROC("glOrthox");
	bglPixelStorei = GETPROC("glPixelStorei");
	bglPointParameterx = GETPROC("glPointParameterx");
	bglPointParameterxv = GETPROC("glPointParameterxv");
	bglPointSizex = GETPROC("glPointSizex");
	bglPolygonOffsetx = GETPROC("glPolygonOffsetx");
	bglPopMatrix = GETPROC("glPopMatrix");
	bglPushMatrix = GETPROC("glPushMatrix");
	bglReadPixels = GETPROC("glReadPixels");
	bglRotatex = GETPROC("glRotatex");
	bglSampleCoverage = GETPROC("glSampleCoverage");
	bglSampleCoveragex = GETPROC("glSampleCoveragex");
	bglScalex = GETPROC("glScalex");
	bglScissor = GETPROC("glScissor");
	bglShadeModel = GETPROC("glShadeModel");
	bglStencilFunc = GETPROC("glStencilFunc");
	bglStencilMask = GETPROC("glStencilMask");
	bglStencilOp = GETPROC("glStencilOp");
	bglTexCoordPointer = GETPROC("glTexCoordPointer");
	bglTexEnvi = GETPROC("glTexEnvi");
	bglTexEnvx = GETPROC("glTexEnvx");
	bglTexEnviv = GETPROC("glTexEnviv");
	bglTexEnvxv = GETPROC("glTexEnvxv");
	bglTexImage2D = GETPROC("glTexImage2D");
	bglTexParameteri = GETPROC("glTexParameteri");
	bglTexParameterx = GETPROC("glTexParameterx");
	bglTexParameteriv = GETPROC("glTexParameteriv");
	bglTexParameterxv = GETPROC("glTexParameterxv");
	bglTexSubImage2D = GETPROC("glTexSubImage2D");
	bglTranslatex = GETPROC("glTranslatex");
	bglVertexPointer = GETPROC("glVertexPointer");
	bglViewport = GETPROC("glViewport");
}

void GLESDeInit()
{
	bglAlphaFunc = NULL;
	bglClearColor = NULL;
	bglClearDepthf = NULL;
	bglClipPlanef = NULL;
	bglColor4f = NULL;
	bglDepthRangef = NULL;
	bglFogf = NULL;
	bglFogfv = NULL;
	bglFrustumf = NULL;
	bglGetClipPlanef = NULL;
	bglGetFloatv = NULL;
	bglGetLightfv = NULL;
	bglGetMaterialfv = NULL;
	bglGetTexEnvfv = NULL;
	bglGetTexParameterfv = NULL;
	bglLightModelf = NULL;
	bglLightModelfv = NULL;
	bglLightf = NULL;
	bglLightfv = NULL;
	bglLineWidth = NULL;
	bglLoadMatrixf = NULL;
	bglMaterialf = NULL;
	bglMaterialfv = NULL;
	bglMultMatrixf = NULL;
	bglMultiTexCoord4f = NULL;
	bglNormal3f = NULL;
	bglOrthof = NULL;
	bglPointParameterf = NULL;
	bglPointParameterfv = NULL;
	bglPointSize = NULL;
	bglPolygonOffset = NULL;
	bglRotatef = NULL;
	bglScalef = NULL;
	bglTexEnvf = NULL;
	bglTexEnvfv = NULL;
	bglTexParameterf = NULL;
	bglTexParameterfv = NULL;
	bglTranslatef = NULL;
	bglActiveTexture = NULL;
	bglAlphaFuncx = NULL;
	bglBindBuffer = NULL;
	bglBindTexture = NULL;
	bglBlendFunc = NULL;
	bglBufferData = NULL;
	bglBufferSubData = NULL;
	bglClear = NULL;
	bglClearColorx = NULL;
	bglClearDepthx = NULL;
	bglClearStencil = NULL;
	bglClientActiveTexture = NULL;
	bglClipPlanex = NULL;
	bglColor4ub = NULL;
	bglColor4x = NULL;
	bglColorMask = NULL;
	bglColorPointer = NULL;
	bglCompressedTexImage2D = NULL;
	bglCompressedTexSubImage2D = NULL;
	bglCopyTexImage2D = NULL;
	bglCopyTexSubImage2D = NULL;
	bglCullFace = NULL;
	bglDeleteBuffers = NULL;
	bglDeleteTextures = NULL;
	bglDepthFunc = NULL;
	bglDepthMask = NULL;
	bglDepthRangex = NULL;
	bglDisable = NULL;
	bglDisableClientState = NULL;
	bglDrawArrays = NULL;
	bglDrawElements = NULL;
	bglEnable = NULL;
	bglEnableClientState = NULL;
	bglFinish = NULL;
	bglFlush = NULL;
	bglFogx = NULL;
	bglFogxv = NULL;
	bglFrontFace = NULL;
	bglFrustumx = NULL;
	bglGetBooleanv = NULL;
	bglGetBufferParameteriv = NULL;
	bglGetClipPlanex = NULL;
	bglGenBuffers = NULL;
	bglGenTextures = NULL;
	bglGetError = NULL;
	bglGetFixedv = NULL;
	bglGetIntegerv = NULL;
	bglGetLightxv = NULL;
	bglGetMaterialxv = NULL;
	bglGetPointerv = NULL;
	bglGetString = NULL;
	bglGetTexEnviv = NULL;
	bglGetTexEnvxv = NULL;
	bglGetTexParameteriv = NULL;
	bglGetTexParameterxv = NULL;
	bglHint = NULL;
	bglIsBuffer = NULL;
	bglIsEnabled = NULL;
	bglIsTexture = NULL;
	bglLightModelx = NULL;
	bglLightModelxv = NULL;
	bglLightx = NULL;
	bglLightxv = NULL;
	bglLineWidthx = NULL;
	bglLoadIdentity = NULL;
	bglLoadMatrixx = NULL;
	bglLogicOp = NULL;
	bglMaterialx = NULL;
	bglMaterialxv = NULL;
	bglMatrixMode = NULL;
	bglMultMatrixx = NULL;
	bglMultiTexCoord4x = NULL;
	bglNormal3x = NULL;
	bglNormalPointer = NULL;
	bglOrthox = NULL;
	bglPixelStorei = NULL;
	bglPointParameterx = NULL;
	bglPointParameterxv = NULL;
	bglPointSizex = NULL;
	bglPolygonOffsetx = NULL;
	bglPopMatrix = NULL;
	bglPushMatrix = NULL;
	bglReadPixels = NULL;
	bglRotatex = NULL;
	bglSampleCoverage = NULL;
	bglSampleCoveragex = NULL;
	bglScalex = NULL;
	bglScissor = NULL;
	bglShadeModel = NULL;
	bglStencilFunc = NULL;
	bglStencilMask = NULL;
	bglStencilOp = NULL;
	bglTexCoordPointer = NULL;
	bglTexEnvi = NULL;
	bglTexEnvx = NULL;
	bglTexEnviv = NULL;
	bglTexEnvxv = NULL;
	bglTexImage2D = NULL;
	bglTexParameteri = NULL;
	bglTexParameterx = NULL;
	bglTexParameteriv = NULL;
	bglTexParameterxv = NULL;
	bglTexSubImage2D = NULL;
	bglTranslatex = NULL;
	bglVertexPointer = NULL;
	bglViewport = NULL;
}

#endif // USE_ANGLE_GLES